### ISSUE TITLE
[Feat] 문과 사람 사이의 거리 측정

### ISSUE THREAD

**Issue by hotsunnyday** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#105]
- 현재 문 인식 관련 모델이 없는 관계로 SceneKit에 있는 문 인식 기능을 활용한 중입니다.
- SceneKit에서 인식한 문과 아이폰 카메라의 거리를 측정할 예정입니다.

**Comment by garlicvread** [comment]
금일~내일 중으로 문 인식 모델 학습 시작해 보도록 하겠습니다.
