### ISSUE TITLE
[Bug] SoundManager 클래스의 사용중 블루투스이어폰이 연결되거나 끊길때 앱크래시 문제 

### ISSUE THREAD

**Issue by mizz0224** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#108]
SoundManger 클래스로 객체 생성시 init() 메서드의 오디오세션 설정때문에 SoundManger 클래스 객체 생성후 블루투스 이어폰이 연결되거나 끊길때 앱이 비정상적으로 종료되는 오류를 발견했습니다.

**Comment by garlicvread** [comment]
아하 이거 때문에 강종되는 거였음?

**Comment by mizz0224** [comment]
> 아하 이거 때문에 강종되는 거였음?

음... Oculu 에서는 확인하지 못했는데, 제 개인테스트앱에서는 이 문제가 발생하더라구요 그래서 수정했고 제가 개인적으로 테스트해본결과 일단 오류는 해결한듯 합니다.
