### ISSUE TITLE
[Help] 걸음수를 안내할때 한자가 아닌 고유어로 유저에게 피드백하는건 어떨까요?

### ISSUE THREAD

**Issue by mizz0224** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#118]
먼저 자극적인 제목 죄송합니다
제목의 정확한뜻은 현재 한국어에서 숫자를 세는 말중에
일(1)이(2)삼(3)사(4)오(5) 는 한자어와
하나또는 한(1) 둘(2) 셋(3) 넷(4) 다섯(5)이라는 고유어가 있습니다.
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=45121
국립국어원의 답변 참고

저는 한자어도 사용하지만, 걸음을 안내할경우에 한걸음, 두걸음, 세걸음 과같이 표현하지 일걸음, 이걸음, 세걸음 이라고 표현하지 않아 어색하다고 느껴집니다.

현재 문까지 남아있는 거리를안내할때, "문까지 오(5)걸음 남았습니다" 와같이 한자어로 표현하는 부분이있는데 이 말이 조금어색해서 현재 문까지 남아있는 거리를안내할때, "문까지 다섯(5)걸음 남았습니다"로 피드백을 주는편이 조금 매끄럽게 느껴진다고 느껴져서 고유어로 변경하는 편이 어떨까하여 건의드립니다.

**Comment by garlicvread** [comment]
아 일 걸음 이 걸음 이런 식으로 안내해 줘?
그럼 한 걸음 두 걸음으로 바꿔야지!

**Comment by YunSeok-Choi** [comment]
확실히 듣기에 어색한 표현이네요! 
변경하는게 좋은 것 같습니다👍👍

**Comment by hotsunnyday** [comment]
제가 직접 실험해보니까 문을 다섯걸음 떨어졌을 때 부터 인식합니다. 이 부분 참고해서 만들면 될 것 같습니다.

**Comment by garlicvread** [comment]
> 제가 직접 실험해보니까 문을 다섯걸음 떨어졌을 때 부터 인식합니다. 이 부분 참고해서 만들면 될 것 같습니다.

다섯 걸음 정도면 딱 적당하다 싶습니다!

**Comment by hotsunnyday** [comment]
구현이 완료된 사항이여서 대신 이슈를 닫습니다.

**Comment by garlicvread** [comment]
> 구현이 완료된 사항이여서 대신 이슈를 닫습니다.

관련 커밋을 링크로 남겨주시면 더 좋을 것 같습니다!
