### ISSUE TITLE
[Feat] 기능 전환용 버튼 매핑

### ISSUE THREAD

**Issue by garlicvread** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#13]
### 현재 기능
- 다음 기능이 순서를 이루고 있음
  - 내비게이션: 장애물 탐지
  - 주변환경 인지: 건물 출입구나 실내 출입문의 위치, 문 종류, 문고리 위치 등에 대한 안내
  - 문자 인지: 버스 노선번호, 강의실 번호, 간판 등에 대한 안내<br><br>

### 기능 매핑
- 볼륨 업/다운 + 전원 버튼 3회 프레스
  - 업: 현재 기능의 이전 기능으로 이동/선택
  - 다운: 현재 기능의 다음 기능으로 이동/선택
  - 전원 버튼 3회 프레스: 선택한 기능의 실행

**Comment by Tempnixk** [comment]
제가 이 부분 맡겠습니다~

**Comment by garlicvread** [comment]
애플 앱스토어 정책상 취소
다른 방식 UI 구현으로 전환
