### ISSUE TITLE
[Feat] 문인식, 글자인식 관련 Localization 추가

### ISSUE THREAD

**Issue by hotsunnyday** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#135]
- 문인식과 글자인식이 한국어만 존재하는 관계로
- 버튼의 Text와 같은 정적인 요소와 TTS를 하는 요소로 나누어야 합니다.
- 추가로 영어의 경우 영어 TTS음성이 나오도록 변경할 예정입니다.

**Comment by garlicvread** [comment]
이 이슈는 #136 커밋으로 해결했습니다!
이슈 닫아주세용 @hotsunnyday
