### ISSUE TITLE
[Feat] 근접센서 동작 navigation에서만 작동하도록 변경

### ISSUE THREAD

**Issue by hotsunnyday** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#140]
- 메인 뷰에서 작동중인 근접 센서를 navigation을 실행한 경우에만 작동하도록 변경할 예정입니다.
- 이제 디바이스 상태 관련 안내를 TTS/VoiceOver를 통해 전달할 예정입니다.
- 추가로 TTS 말하기 속도를 변경할 예정입니다.

**Comment by garlicvread** [comment]
굿굿
