### ISSUE TITLE
[Feat] 근접 센서 적용

### ISSUE THREAD

**Issue by hotsunnyday** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#15]
- 디바이스를 착용 후 오입력 방지와 디스플레이 전력 소모를 줄이기 위해 근접 센서를 활성화 시킵니다.

**Comment by garlicvread** [comment]
> * 디바이스를 착용 후 오입력 방지와 디스플레이 전력 소모를 줄이기 위해 근접 센서를 활성화 시킵니다.

OLED 기준, 손에 들고 사용할 때도 전력 소모를 방지할 수 있도록 까만 rectangle 하나 덮어도 나쁘지 않을 것 같네용!

**Comment by hotsunnyday** [comment]
적용 완료하여 이슈 종료합니다.
