### ISSUE TITLE
[Feat] TextReader 기능 추가

### ISSUE THREAD

**Issue by hotsunnyday** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#59]
- Main View에 Text Reader 버튼에 Text Reader 기능을 추가합니다.
- 데모로 만들어지는 앱이기 때문에 카메라 화면을 보여주고, VoiceOver가 적용되지 않은 UI를 적용할 예정입니다.
- 카메라 화면을 터치하면 프레임에서 LiveText 를 통해 글자를 인식합니다.
- 글자를 인식할 경우, TTS를 통해 읽습니다.

**Comment by garlicvread** [comment]
좋아용!
