### ISSUE TITLE
[Bug] MainView, ObjectDetectionView에서 화면회전시 깨지는 현상 발생

### ISSUE THREAD

**Issue by mizz0224** [ADA-1st-macro-walikngAssistant/WalkingAssistant_iOS#71]
MainView, ObjectDetectionView에서 화면회전시 깨지는 현상이 발생했습니다. 
발생했을때 화면은 다음과같습니다.
![IMG_0010 2](https://user-images.githubusercontent.com/61971962/201064096-06e7e2cc-052d-41f9-be4f-50fdf3d90544.PNG)
![IMG_0011](https://user-images.githubusercontent.com/61971962/201064440-8f4e7b01-ec2b-46f9-a34c-cda56013ad11.PNG)

캡쳐하지 못했지만 이외에도 깨지는현상이 다수 발생했습니다. 확인부탁드립니다.

**Comment by garlicvread** [comment]
이슈 제가 잡겠습니다.

**Comment by garlicvread** [comment]
Close with #75
